config/routes.rb
Rails.application.routes.draw do
  resources :sweets, only: %i[index show]
  resources :vendors, only: %i[index show]
  resources :vendor_sweets, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sweet.rb
class Sweet < ApplicationRecord
  has_many :vendor_sweets
  has_many :vendors, through: :vendor_sweets
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  has_many :vendor_sweets
  has_many :sweets, through: :vendor_sweets
end

app/models/vendor_sweet.rb
class VendorSweet < ApplicationRecord
  belongs_to :vendor
  belongs_to :sweet

  validates :vendor, :sweet, :comment, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sweets_controller.rb
class SweetsController < ApplicationController
  def index
    @sweets = Sweet.all
  end

  def show
    @sweet = Sweet.find(params[:id])
  end
end

app/controllers/vendor_sweets_controller.rb
class VendorSweetsController < ApplicationController
  def create
    @vendor_sweet = VendorSweet.new(vendor_sweet_params)
    @vendor = @vendor_sweet.vendor

    if @vendor_sweet.save
      redirect_to vendor_path(@vendor)
    else
      render "vendors/show"
    end
  end

  private

  def vendor_sweet_params
    params.require(:vendor_sweet).permit(:vendor_id, :sweet_id, :comment)
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def index
    @vendors = Vendor.all
  end

  def show
    @vendor = Vendor.find(params[:id])
    @vendor_sweet = VendorSweet.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsImmersiveAssessmentAlternateFirstRound</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sweets/index.html.erb
<h1>All Sweets</h1>

<ul>
  <% @sweets.each do |sweet| %>
    <li><%= link_to sweet.name, sweet_path(sweet) %></li>
  <% end  %>
</ul>

app/views/sweets/show.html.erb
<h1><%= @sweet.name %></h1>

<h2>Vendors</h2>
<ul>
  <% @sweet.vendors.each do |vendor| %>
    <li><%= link_to vendor.name, vendor_path(vendor) %></li>
  <% end %>
</ul>

app/views/vendors/index.html.erb
<h1>All Vendors</h1>

<ul>
  <% @vendors.each do |vendor| %>
    <li><%= link_to vendor.name, vendor_path(vendor) %></li>
  <% end  %>
</ul>

app/views/vendors/show.html.erb
<% if @vendor_sweet.errors.any? %>
  <h2><%= pluralize(@vendor_sweet.errors.count, "error") %> prohibited saving:</h2>

  <ul>
    <% @vendor_sweet.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1><%= @vendor.name %></h1>

<h2>Sweets</h2>
<ul>
  <% @vendor.vendor_sweets.each do |vendor_sweet| %>
    <li><%= vendor_sweet.sweet.name %>: <%= vendor_sweet.comment %></li>
  <% end %>
</ul>

<h2>Add Sweet</h2>
<%= form_with model: @vendor_sweet, local: true do |f| %>
  <%= f.hidden_field :vendor_id, value: @vendor.id %>

  <div>
    <%= f.label :sweet_id %>
    <br>
    <%= f.collection_select :sweet_id, Sweet.all, :id, :name, include_blank: "PICK ONE!!!!!!" %>
  </div>

  <div>
    <%= f.label :comment %>
    <br>
    <%= f.text_field :comment %>
  </div>

  <%= f.submit %>
<% end %>